spring.application.name=ProjectManager
spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql